### ISSUE TITLE
BSOD when removing non-empty bus

### ISSUE THREAD

**Issue by shauleiz** [nefarius/ScpVBus#2]
## Description ##
Crash when removing ScpVBus that has a virtual Xbox device attached to it.

## Reproduction ##
1. **Install**: devcon.exe install ScpVBus.inf root\scpvbus
2. Add one virtual device
3. **Uninstall**: devcon.exe remove \*Scp\* -> "Removed on Reboot"
4. Not rebooting.
5. Using Device Manager, Scan for Hardware Changes
6. BSOD

## Discussion ##
As seen in the attached dump file:
[032616-66812-01.zip](https://github.com/nefarius/ScpVBus/files/190524/032616-66812-01.zip)
Function Bus_DestroyPdo tries to access a not existing  ParentFdo.

In case you cannot open the file, here is a short summery:
**Call Stack:**
Bus_DestroyPdo
Bus_PDO_PnP
Bus_PnP

The crash is here: **fdoData = FDO_FROM_PDO(PdoData);**
Reason: **ParentFdo = 0**

**Comment by nefarius** [comment]
Can confirm, can reproduce, could fix :) Thanks for reporting.

**Comment by shauleiz** [comment]
Tested and is fixed.
Thank you very much!

**Comment by nefarius** [comment]
Good to hear :) btw. I'm way behind on your mail responses, I apologize. Will work on them soon!
